//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabrApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public int PostId { get; set; }
        public string PostUrl { get; set; }
        public string PostTitle { get; set; }
        public System.DateTime Date { get; set; }
        public int Score { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
